name: Continuous Deployment

on:
  push:
    branches:
      - main
      - feature/ci-cd

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t stu_startup_mng_collab_platform .

      - name: Docker remove old container
        run: docker container rm stu_startup_fe

      - name: Docker run
        run: docker run -d --name stu_startup_fe -p 3333:80 stu_startup_mng_collab_platform
